tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "autoconf"
brew "cloc"
brew "ghq"
brew "gibo"
brew "git"
brew "git-secrets"
brew "go"
brew "hub"
brew "imagemagick"
brew "libyaml"
brew "lua"
brew "luajit"
brew "mas"
brew "nkf"
brew "node"
brew "pcre"
brew "peco"
brew "perl"
brew "pre-commit"
brew "ruby-build"
brew "rbenv"
brew "ruby"
brew "shellcheck"
brew "source-highlight"
brew "the_platinum_searcher"
brew "tig"
brew "tldr"
brew "vim"
brew "zplug"
brew "heroku/brew/heroku"
cask "appcleaner"
cask "boostnote"
cask "clipy"
cask "dash"
cask "docker"
cask "dropbox"
cask "google-chrome"
cask "iterm2"
cask "jasper"
cask "kitematic"
cask "postman"
cask "qfinder-pro"
cask "sequel-pro"
cask "spotify"
cask "station"
cask "visual-studio-code"
cask "vlc"
mas "com.apple.dt.Xcode", id: 497799835
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.apple.iWork.Numbers", id: 409203825
mas "com.apple.iWork.Pages", id: 409201541
mas "com.readitlater.PocketMac", id: 568494494
mas "com.tinyspeck.slackmacgap", id: 803453959
mas "cx.c3.theunarchiver", id: 425424353
mas "jp.naver.line.mac", id: 539883307
