tap "goodwithtech/dockle"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "ktr0731/evans"
tap "songmu/tap"
cask "adoptopenjdk"
brew "autoconf"
brew "automake"
brew "python"
brew "awscli"
brew "cloc"
brew "composer"
brew "direnv"
brew "libpng"
brew "fzf"
brew "jpeg"
brew "ghq"
brew "gibo"
brew "git"
brew "git-secrets"
brew "pcre"
brew "go"
brew "jasper"
brew "graphviz"
brew "grpcurl"
brew "hub"
brew "imagemagick"
brew "jq"
brew "libxml2"
brew "lua"
brew "luajit"
brew "make"
brew "mas"
brew "mcrypt"
brew "mysql-client"
brew "nkf"
brew "node"
brew "peco"
brew "perl"
brew "php"
brew "plantuml"
brew "pre-commit"
brew "protobuf"
brew "ruby-build"
brew "rbenv"
brew "re2c"
brew "ruby"
brew "shellcheck"
brew "source-highlight"
brew "the_platinum_searcher"
brew "tig"
brew "tldr"
brew "vim"
brew "zplug"
brew "zsh"
brew "goodwithtech/dockle/dockle"
brew "heroku/brew/heroku"
brew "ktr0731/evans/evans"
brew "songmu/tap/blogsync"
cask "alfred"
cask "appcleaner"
cask "boostnote"
cask "cheatsheet"
cask "clipy"
cask "dash"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "google-photos-backup-and-sync"
cask "graphiql"
cask "iterm2"
cask "jasper"
cask "kitematic"
cask "krisp"
cask "postman"
cask "qfinder-pro"
cask "sequel-pro"
cask "spotify"
cask "station"
cask "townwifi"
cask "trailer"
cask "visual-studio-code"
cask "vlc"
mas "Bitwarden", id: 1352778147
mas "Hex Fiend", id: 1342896380
mas "Keynote", id: 409183694
mas "Lightshot Screenshot", id: 526298438
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
