tap "bufbuild/buf"
tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "itchyny/tap"
tap "ktr0731/evans"
tap "mono0926/license-plist"
tap "muesli/tap"
tap "reviewdog/tap"
tap "sanemat/font"
tap "songmu/tap"
tap "zkokaja/brewlet"
brew "libpng"
brew "autoconf"
brew "automake"
brew "awscli"
brew "bat"
brew "pcre"
brew "circleci"
brew "clang-format"
brew "cloc"
brew "cmake"
brew "jpeg"
brew "php", restart_service: true
brew "composer"
brew "direnv"
brew "python@3.9"
brew "fzf"
brew "gh"
brew "ghq"
brew "gibo"
brew "git"
brew "git-secrets"
brew "gnu-sed"
brew "go"
brew "golangci-lint"
brew "jasper", link: false
brew "netpbm"
brew "graphviz"
brew "gron"
brew "grpcurl"
brew "hadolint"
brew "hub"
brew "hugo"
brew "imagemagick"
brew "jq"
brew "libxml2"
brew "lsd"
brew "lua"
brew "luajit"
brew "make"
brew "mas"
brew "mcrypt"
brew "mysql-client"
brew "nkf"
brew "peco"
brew "perl"
brew "pre-commit"
brew "protobuf"
brew "ruby-build"
brew "rbenv"
brew "re2c"
brew "redis", restart_service: true
brew "ripgrep"
brew "ruby"
brew "shellcheck"
brew "source-highlight"
brew "starship"
brew "the_platinum_searcher"
brew "tig"
brew "tldr"
brew "tokei"
brew "topgrade"
brew "vim"
brew "zplug"
brew "zsh"
brew "bufbuild/buf/buf"
brew "heroku/brew/heroku"
brew "itchyny/tap/mmv"
brew "ktr0731/evans/evans"
brew "muesli/tap/duf"
brew "reviewdog/tap/reviewdog"
brew "sanemat/font/ricty", args: ["with-powerline"]
brew "songmu/tap/blogsync"
cask "altair-graphql-client"
cask "appcleaner"
cask "authy"
cask "calibre"
cask "docker"
cask "dropbox"
cask "firefox"
cask "imageoptim"
cask "iterm2"
cask "jasper"
cask "karabiner-elements"
cask "monitorcontrol"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "sequel-pro-nightly"
cask "session-manager-plugin"
cask "spotify"
cask "townwifi"
cask "visual-studio-code"
mas "Bitwarden", id: 1352778147
mas "HEIC Converter", id: 1294126402
mas "Hex Fiend", id: 1342896380
mas "Keynote", id: 409183694
mas "Lightshot Screenshot", id: 526298438
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pasta", id: 1438389787
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Unsplash Wallpapers", id: 1284863847
