version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: koalaman/shellcheck-alpine

jobs:
  shellcheck:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Run shellcheck
          command: bin/shellcheck.sh

workflows:
  lint:
    jobs: 
      - shellcheck
